#!/bin/bash
#SBATCH -N 1 
#SBATCH --ntasks-per-node=10
#SBATCH --job-name=articles_seq_model_NLP
#SBATCH --error=articles.%J.error
#SBATCH --output=articles.%J.out
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
cd /home/arpitmehta.cse18.iitbhu/NLP2/POS_comparison_models/sequence-labeler-master
module load conda-python/3.7 cuda/10.1

python experiment.py conf/fcepublic_articles.conf

